# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MardinGunesi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'PMSuperButton'
	pod 'ImageSlideshow', '~> 1.8'
	pod 'ImageSlideshow'

  # Pods for MardinGunesi

end
